{{- $root := . -}}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # DO NOT INJECT THIS AHEAD OF TIME!
  # annotations:
  #   alpha.istio.io/sidecar: injected
  #   alpha.istio.io/version: jenkins@ubuntu-16-04-build-de3bbfab70500-0.1.5-21f4cb4
  #   pod.beta.kubernetes.io/init-containers: '[{"args":["-p","15001","-u","1337"],"image":"docker.io/istio/init:0.1","imagePullPolicy":"Always","name":"init","securityContext":{"capabilities":{"add":["NET_ADMIN"]}}},{"args":["-c","sysctl -w kernel.core_pattern=/tmp/core.%e.%p.%t \u0026\u0026 ulimit -c unlimited"],"command":["/bin/sh"],"image":"alpine","imagePullPolicy":"Always","name":"enable-core-dump","securityContext":{"privileged":true}}]'
  name: "{{ $root.serviceName }}"
  # namespace: "{{ $root.teamName }}"
  labels:
    app: "{{ $root.serviceName }}"
    environment: "{{ $root.environment }}"
    version: "{{ $root.version }}"
spec:
  replicas: {{ $root.replicas }}
  template:
    metadata:
      labels:
        app: "{{ $root.serviceName }}"
        environment: "{{ $root.environment }}"
        version: "{{ $root.version }}"
    spec:
      containers:
      - name: "{{ $root.serviceName }}"
        image: "{{ $root.imageRepo }}/{{ $root.imageService }}:{{ $root.imageTag }}"
        ports:
        - name: "{{ $root.portName }}"
          containerPort: 8080
        command:
        - /a.out
        - -v={{ $root.logLevel }}
        - -logtostderr
        - -port=8080
      # DO NOT INJECT THIS AHEAD OF TIME!
      # - name: proxy
      #   image: docker.io/istio/proxy_debug:0.1
      #   args:
      #   - proxy
      #   - sidecar
      #   - -v
      #   - "2"
      #   - --namespace
      #   - default
      #   env:
      #   - name: POD_NAME
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: metadata.name
      #   - name: POD_IP
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: status.podIP
      #   imagePullPolicy: Always
      #   resources: {}
      #   securityContext:
      #     runAsUser: 1337
